# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
revisionHistoryLimit: 1
image:
  repository: mycluster.icp:8500/default
  name: trader
  tag: classic
  pullPolicy: Always
  containerPort:
    http: 9080
    https: 9443
  resources:
    requests:
      cpu: 200m
      memory: 300Mi
service:
  # Change this to ClusterIP before releasing charts so microservices can only be reached through the ingress
  type: NodePort
  servicePort:
    http: 9080
    https: 9443
secret:
  jwt:
    create: false
    secret_name: stocktrader-jwt
    # audience: stock-trader
    audience: c3RvY2stdHJhZGVy
    # issuer: http://stock-trader.ibm.com
    issuer: aHR0cDovL3N0b2NrLXRyYWRlci5pYm0uY29t
portfolio:
  portfolio_service: portfolio
  portfolio_service_port: "9080"
  portfolio_service_context: "portfolio"
