#Configure the ingress
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{  .Chart.Name }}
  annotations:
    ingress.kubernetes.io/rewrite-target: /trader
spec:
  rules:
  - host:
    http:
      paths:
        path: /trader
      - backend:
          serviceName: trader-service
          servicePort: {{ .Values.service.servicePort.http }}
